In [88]:
import matplotlib.pyplot as plt
import numpy as np
import random
from ipywidgets import interact, widgets


A)

In [89]:
center = [0, 0]


def update_plot(r, p):
    theta = np.linspace(0, 2 * np.pi, 1000)
    r_factor = (r / ((np.abs(np.cos(theta)) ** p + np.abs(np.sin(theta)) ** p) ** (1 / p)))
    x = r_factor * np.cos(theta)
    y = r_factor * np.sin(theta)
    _, ax = plt.subplots(figsize=(5, 5))
    ax.plot(x, y)
    ax.set_xlim(-r - 1, r + 1)
    ax.set_ylim(-r - 1, r + 1)
    plt.xlabel("X-axis")
    plt.ylabel("Y-axis")
    plt.grid(True)
    plt.show()


# Create an interactive slider to adjust the radius
radius_slider = widgets.FloatSlider(
    value=1.0, min=1.0, max=2.0, step=0.1, description="Radius"
)
p_slider = widgets.FloatSlider(value=2, min=1, max=10, step=1, description="p")

# Create an interactive plot
interact(update_plot, r=radius_slider, p=p_slider)

interactive(children=(FloatSlider(value=1.0, description='Radius', max=2.0, min=1.0), FloatSlider(value=2.0, d…

<function __main__.update_plot(r, p)>

B)

In [90]:
def random_vector(n, alpha, p):
    random_vector = np.array([random.uniform(0, 100) for _ in range(n)])
    norm = np.linalg.norm(random_vector, ord=p)
    a = (random_vector/norm)*alpha
    return a

In [91]:
def generate_points(n, alpha, p):
    points = []
    for i in range(1,6):
        v = random_vector(n, alpha, p)
        points.append(v)
    return(points)

With Euclidean norm

In [92]:
generate_points(10, 0.05, 2)

[array([0.00600976, 0.01268963, 0.0161546 , 0.01765629, 0.00660875,
        0.00350183, 0.02115165, 0.02194693, 0.02455125, 0.01193223]),
 array([0.02338008, 0.00612159, 0.00909229, 0.00244278, 0.00191814,
        0.01634202, 0.01741976, 0.02660798, 0.02259915, 0.0058623 ]),
 array([0.02087695, 0.02022538, 0.00781007, 0.00960713, 0.00714028,
        0.02513593, 0.01136364, 0.01262692, 0.0030017 , 0.02283447]),
 array([0.02391198, 0.00975546, 0.00720212, 0.00901524, 0.01363507,
        0.00821777, 0.01737422, 0.00054278, 0.02146578, 0.02614419]),
 array([0.01798528, 0.02059423, 0.02121925, 0.00359893, 0.00457935,
        0.01698106, 0.01885621, 0.00810849, 0.01134445, 0.02073333])]

With Manhattan norm

In [93]:
generate_points(10, 0.05, 1)

[array([0.00249534, 0.00150485, 0.00250026, 0.0086564 , 0.0068436 ,
        0.00168356, 0.00596034, 0.00875135, 0.00967025, 0.00193405]),
 array([0.00944492, 0.00102132, 0.0008754 , 0.00254286, 0.00511293,
        0.00304404, 0.00813618, 0.00579855, 0.00639405, 0.00762976]),
 array([0.00500566, 0.00938231, 0.00563106, 0.00141148, 0.00978354,
        0.00067437, 0.00936484, 0.00252886, 0.00024539, 0.0059725 ]),
 array([0.00656931, 0.00312984, 0.00356819, 0.00674352, 0.00594566,
        0.0038203 , 0.00468824, 0.00598767, 0.0056007 , 0.00394657]),
 array([8.82578617e-04, 3.58207926e-03, 2.91337735e-03, 5.50974143e-03,
        7.96719533e-03, 7.98745801e-05, 5.16302967e-03, 8.01357434e-03,
        7.94051847e-03, 7.94803096e-03])]

With Chebyshov norm

In [94]:
generate_points(10, 0.05, np.inf)

[array([0.03761458, 0.05      , 0.00334287, 0.00865625, 0.01424104,
        0.02592608, 0.04934712, 0.00068145, 0.03704097, 0.0016348 ]),
 array([0.04653744, 0.01336397, 0.03489177, 0.05      , 0.04722218,
        0.04918808, 0.04726157, 0.01002338, 0.03972069, 0.02237297]),
 array([0.02087494, 0.04527922, 0.00326271, 0.03990592, 0.02333887,
        0.00243497, 0.00804855, 0.05      , 0.02661376, 0.00754613]),
 array([0.01131131, 0.00057461, 0.04990025, 0.02482363, 0.03663821,
        0.05      , 0.01739025, 0.02508379, 0.01854493, 0.0148553 ]),
 array([0.03261484, 0.04176221, 0.01311114, 0.01765898, 0.04117599,
        0.05      , 0.00401642, 0.01598602, 0.00741824, 0.04933487])]