# Problema 3

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import random
from ipywidgets import interact, widgets

A)

In [2]:
def update_plot(r, p):
    theta = np.linspace(0, 2 * np.pi, 1000)
    r_factor = (r / ((np.abs(np.cos(theta)) ** p + np.abs(np.sin(theta)) ** p) ** (1 / p)))
    x = r_factor * np.cos(theta)
    y = r_factor * np.sin(theta)
    plt.figure(figsize=(5, 5))
    plt.plot(x, y)
    plt.xlim(-r - 1, r + 1)
    plt.ylim(-r - 1, r + 1)
    plt.xlabel("X-axis")
    plt.ylabel("Y-axis")
    plt.grid(True)
    plt.show()

# Create an interactive slider to adjust the radius
radius_slider = widgets.FloatSlider(
    value=1.0, min=1.0, max=2.0, step=0.1, description="Radius"
)
#p_slider = widgets.FloatSlider(value=2, min=1, max=10, step=1, description="p")
p_slider = widgets.Dropdown(options=[1, 2, 3, 1000],value=2, description="p", disabled=False,)

# Create an interactive plot
interact(update_plot, r=radius_slider, p=p_slider)

interactive(children=(FloatSlider(value=1.0, description='Radius', max=2.0, min=1.0), Dropdown(description='p'…

<function __main__.update_plot(r, p)>

B)

In [3]:
def random_vector(n, alpha, p):
    random_vector = np.array([random.uniform(0, 100) for _ in range(n)])
    norm = np.linalg.norm(random_vector, ord=p)
    a = (random_vector/norm)*alpha
    return a

In [4]:
def generate_points(n, alpha, p):
    points = []
    for i in range(1,6):
        v = random_vector(n, alpha, p)
        points.append(v)
    return(points)

With Euclidean norm

In [5]:
generate_points(10, 0.05, 2)

[array([0.00556667, 0.01617728, 0.00320746, 0.01512828, 0.01097007,
        0.02244368, 0.02380068, 0.01723097, 0.01811389, 0.01235321]),
 array([0.0131529 , 0.0013176 , 0.01102917, 0.02293984, 0.00350525,
        0.02521261, 0.00772621, 0.02686985, 0.00213941, 0.01559372]),
 array([0.01780501, 0.0195426 , 0.03303007, 0.00547892, 0.01138732,
        0.0173018 , 0.00151651, 0.01143637, 0.00519276, 0.00953864]),
 array([0.02226166, 0.00288776, 0.02363905, 0.00441149, 0.00871745,
        0.01264987, 0.01799499, 0.02685381, 0.00689522, 0.00945037]),
 array([0.01385706, 0.01925011, 0.00567275, 0.02175836, 0.01143099,
        0.01006787, 0.01351634, 0.02022821, 0.01736597, 0.01750228])]

With Manhattan norm

In [6]:
generate_points(10, 0.05, 1)

[array([0.005757  , 0.00350608, 0.00171692, 0.00867875, 0.00912632,
        0.0058075 , 0.00702942, 0.00257696, 0.00356665, 0.0022344 ]),
 array([0.00114206, 0.00860528, 0.000676  , 0.00878999, 0.00661837,
        0.00366649, 0.00490967, 0.00782855, 0.00058578, 0.00717781]),
 array([0.00186527, 0.0046975 , 0.00028332, 0.01161646, 0.00999912,
        0.0113089 , 0.00224542, 0.00352239, 0.00118732, 0.0032743 ]),
 array([0.00239497, 0.00622289, 0.00073821, 0.0016571 , 0.00772942,
        0.00863006, 0.00854669, 0.00167494, 0.00364366, 0.00876207]),
 array([0.00330832, 0.00107435, 0.00501735, 0.00145691, 0.00422057,
        0.00529437, 0.00393565, 0.01001189, 0.00647179, 0.00920881])]

With Chebyshov norm

In [7]:
generate_points(10, 0.05, np.inf)

[array([0.0422592 , 0.00085228, 0.05      , 0.01765746, 0.00577371,
        0.04340474, 0.0326811 , 0.00192582, 0.00962651, 0.01034742]),
 array([0.0475722 , 0.04699069, 0.05      , 0.02706239, 0.04460314,
        0.0414822 , 0.02282961, 0.02725785, 0.00217677, 0.02749091]),
 array([0.03484336, 0.05      , 0.01356413, 0.04150937, 0.01026716,
        0.01945639, 0.0333992 , 0.00412356, 0.04745913, 0.0308891 ]),
 array([0.01777049, 0.00606665, 0.0249749 , 0.00644653, 0.01797617,
        0.03796044, 0.01270662, 0.04076718, 0.00072791, 0.05      ]),
 array([0.01658327, 0.04555864, 0.01260252, 0.02530182, 0.0121635 ,
        0.04269598, 0.0460566 , 0.0233487 , 0.01539877, 0.05      ])]