In [41]:
import numpy as np
import math

In [42]:
def generate_hilbert_matrix(n):
    return np.matrix([[1/(i+j+1) for j in range(n)] for i in range(n)])

In [43]:
def minkowski(vector, p = 1):
    if p == math.inf:
        return np.max(np.abs(vector))
    return np.sum(np.abs(vector)**p)**(1/p)

In [44]:
def approximate_norm(A, p = 1):
    rows, cols = A.shape
    results = []
    canonical_vectors = []
    for i in range(cols):
        canonical_vector = np.zeros(cols)
        canonical_vector[i] = 1
        canonical_vector = canonical_vector.reshape(-1, 1)
        canonical_vectors.append(canonical_vector)
        result = np.matmul(A, canonical_vector)
        result = np.array(result)
        results.append(minkowski(result, p))
    print("Distances when multiplying A by each canonical vectors:")
    print(results)
    print("Vector with unit norm that satisfies ||Ax|| to be max:")
    print(canonical_vectors[np.argmax(results)])  



In [45]:
A = generate_hilbert_matrix(10)
A = np.matrix([[2, 6], [7, 8]])

In [46]:
A

matrix([[2, 6],
        [7, 8]])

In [47]:
approximate_norm(A, p = math.inf)

Distances when multiplying A by each canonical vectors:
[7.0, 8.0]
Vector with unit norm that satisfies ||Ax|| to be max:
[[0.]
 [1.]]


In [48]:
def generate_aleatory_matrix(low, high, rows, columns):
    return np.random.randint(low, high + 1, size=(rows, columns))


In [49]:
B = generate_aleatory_matrix(-10, 10, 5, 7)
B

array([[ -2,   1,  -5,  -8,   1,   0,   7],
       [  6,  -8,   5,   3,  -9,   3,   1],
       [  5,  -5,  -1,   2, -10,  -1,   8],
       [  4,  -1,  -5,   3,  -2,  -2,  -6],
       [  7,  -7,  -9,  -2,  -3,   3,  -4]])

In [59]:
B = np.array([[2, -3], [5, -1]])

In [2]:
def max_row(B, p):
    canonical_vectors = []
    absolute_values = np.abs(B)
    max_abs_row_index = np.argmax(np.sum(np.abs(absolute_values), axis=1))
    max_abs_row = B[max_abs_row_index, :]
    signs = np.sign(max_abs_row)
    row, cols = B.shape
    if p == np.inf:
        return print(f"the value for p = {p} norm is: {max(np.dot(B, signs))}")        
    else: 
        for i in range(0,10):
            for i in range(cols):
                canonical_vector = np.zeros(cols)
                canonical_vector[i] = 1
                canonical_vector = canonical_vector.reshape(-1, 1)
                canonical_vectors.append(canonical_vector)
                #hacer promedio e1 y e2
            return print(f"the value for p = {p} norm is: {np.sum(np.abs(B)**p)**(1/p)}")
   

In [73]:
max_row(B, math.inf)

the value for inf norm is: 6


In [61]:
max_row(B, 1)

11.0

In [54]:
l2_norm = np.linalg.norm(B)

print("L2 norm of the matrix:", l2_norm)

L2 norm of the matrix: 6.244997998398398


In [66]:
max_row(B, 2)

the value for inf norm is: 11


In [ ]:
#larger singular value